# Generated by Django 3.2.9 on 2021-12-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty_outlet', '0003_bounty_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='bounty',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='benefactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty_outlet.benefactor'),
        ),
    ]
