# Generated by Django 3.2.9 on 2021-12-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty_outlet', '0004_auto_20211201_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='benefactor',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty_outlet.address'),
        ),
    ]
